apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: s3-loki-credentials
  namespace: grafana
spec:
  path: secret/data/loki/s3
  keys:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  type: Opaque