---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap-tls
spec:
  dnsNames:
    - ldap.bugbear.fr
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: default-issuer
  secretName: openldap-tls
