apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeus-cron-deployment
  labels:
    app: zeus-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeus-cron
  template:
    metadata:
      labels:
        app: zeus-cron
    spec:
      containers:
        - name: zeus-cron-acdc
          image: ghcr.io/renaud-dov/calendar_cron:master
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: bugbear-main-cluster.postgres.svc.cluster.local
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: zeus.cron.bugbear-main-cluster.credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zeus.cron.bugbear-main-cluster.credentials
                  key: password
            - name: DB_DATABASE
              value: zeus
            - name: ICS_URL
              value: https://zeus.ionis-it.com/api/group/51/ics/wndh1411YP?startDate=2024-04-10
            - name: GROUP
              value: ACDC
            - name: FILTER_REGEX
              value: Programmation
            - name: WEBHOOK_URLS
              valueFrom:
                secretKeyRef:
                  name: zeus-secrets
                  key: DISCORD_WEBHOOK_ACDC


