# yamllint disable rule:line-length
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-operator
data:
  enable_cross_namespace_secret: "true"
  secret_name_template: "{username}.{cluster}.credentials"
  enable_crd_validation: "true"