---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: bugbear-main-cluster

spec:
  teamId: "bugbear"
  volume:
    size: 10Gi
  numberOfInstances: 2

  # users: name -> permissions (usually [])
  users: # in form of namespace.name
    # database owner
    hermes.hermes: []
    zeus.cron: []
    grafana.ro: []
    keycloak.keycloak: []

  # databases: name -> owner
  databases:
    hermes: hermes.hermes
    hermes2: hermes.hermes
    zeus: zeus.cron
    keycloak: keycloak.keycloak
  postgresql:
    version: "14"
  sidecars:
    - name: "exporter"
      image: quay.io/prometheuscommunity/postgres-exporter:v0.15.0
      ports:
        - name: exporter
          containerPort: 9187
          protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 256M
        requests:
          cpu: 100m
          memory: 100M
      env:
        - name: DATA_SOURCE_URI
          value: "bugbear-main-cluster?sslmode=require"
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: postgres.bugbear-main-cluster.credentials
              key: username
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: postgres.bugbear-main-cluster.credentials
              key: password
        - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
          value: "true"

