---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: bugbear-main-cluster

spec:
  teamId: "bugbear"
  volume:
    size: 25Gi
  numberOfInstances: 2

  # users: name -> permissions (usually [])
  users: # in form of namespace.name
    # database owner
    hermes.hermes: []
    zeus.cron: []
    grafana.ro: []
    keycloak.keycloak: []
    mailu.mailu: []

  # databases: name -> owner
  databases:
    hermes: hermes.hermes
    hermes2: hermes.hermes
    zeus: zeus.cron
    keycloak: keycloak.keycloak
    mailu: mailu.mailu
    roundcube: mailu.mailu
  postgresql:
    version: "14"
  env:
    - name: WAL_S3_BUCKET
      value: postgres-backup
    - name: WALE_S3_ENDPOINT
      value: "https+path://s3.bugbear.fr:443"
    - name: WALE_DISABLE_S3_SSE
      value: "true"
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: minio-postgres-creds
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-postgres-creds
          key: AWS_SECRET_ACCESS_KEY
  additionalVolumes:
    - name: pgbackup
      mountPath: /home/postgres/pgbackup
      volumeSource:
        emptyDir: { }
  sidecars:
    - name: "exporter"
      image: quay.io/prometheuscommunity/postgres-exporter:v0.17.1
      ports:
        - name: exporter
          containerPort: 9187
          protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 256M
        requests:
          cpu: 100m
          memory: 100M
      env:
        - name: DATA_SOURCE_URI
          value: "bugbear-main-cluster?sslmode=require"
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: postgres.bugbear-main-cluster.credentials
              key: username
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: postgres.bugbear-main-cluster.credentials
              key: password
        - name: PG_EXPORTER_AUTO_DISCOVER_DATABASES
          value: "true"

