---
apiVersion: v1
kind: Service
metadata:
  name: bugbear-main-cluster-rw
spec:
  type: ClusterIP
  selector:
    application: spilo
    cluster-name: bugbear-main-cluster
    spilo-role: master
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql

---
apiVersion: v1
kind: Service
metadata:
  name: bugbear-main-cluster-metrics-master
  labels:
    application: spilo
    spilo-role: master
spec:
  type: ClusterIP
  ports:
    - name: exporter
      port: 9187
      targetPort: exporter
  selector:
    application: spilo
    cluster-name: bugbear-main-cluster
    spilo-role: master
---
apiVersion: v1
kind: Service
metadata:
  name: bugbear-main-cluster-metrics-replica
  labels:
    application: spilo
    spilo-role: replica
spec:
  type: ClusterIP
  ports:
    - name: exporter
      port: 9187
      targetPort: exporter
  selector:
    application: spilo
    cluster-name: bugbear-main-cluster
    spilo-role: replica