# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
spec:
  type: Opaque
  path: secret/data/argocd/oidc
  reconcileStrategy: Merge
  keys:
    - oidc.keycloak.clientId
    - oidc.keycloak.clientSecret

 
