apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.9.0
        args:
        - --source=ingress
        - --domain-filter=bugbear.fr
        - --zone-id-filter=$(CF_ZONE_ID)
        - --provider=cloudflare
        - --cloudflare-proxied # (optional) enable the proxy feature of Cloudflare (DDOS protection, CDN...)
#        - --cloudflare-dns-records-per-page=5000 # (optional) configure how many DNS records to fetch per request
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-key
              key: cloudflare_api_token
        - name: CF_ZONE_ID
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-key
              key: zone_id