apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: cloudflare-api-key
spec:
  path: secret/data/external-dns/cloudflare-api-key
  keys:
    - cloudflare_api_token
    - zone_id
  type: Opaque