---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default-issuer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: default-issuer
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: default-manager
  project: default
  source:
    repoURL: https://gitlab.com/dov_bugbear/infrastructure.git
    targetRevision: HEAD
    path: k8s/manifests/cert-issuer
