# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  labels:
    app: logging
    component: loki
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: grafana
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 5.42.1
      helm:
        values: |
          fullnameOverride: loki
          gateway:
            enabled: false
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: default-issuer
              nginx.ingress.kubernetes.io/auth-type: basic
              nginx.ingress.kubernetes.io/auth-secret: loki-auth-map
              nginx.ingress.kubernetes.io/auth-secret-type: auth-map
              nginx.ingress.kubernetes.io/proxy-body-size: 10m
            hosts:
              - loki.bugbear.fr
            tls:
              - hosts:
                  - loki.bugbear.fr
                secretName: loki-tls
          deploymentMode: SingleBinary
          singleBinary:
            replicas: 1
          
          test:
            enabled: false
          minio:
            enabled: false
          
          write:
            replicas: 0
          read:
            replicas: 0
          backend:
            replicas: 0
          
          loki:
            commonConfig:
              replication_factor: 1
            limits_config:
              max_query_lookback: 744h
              retention_period: 744h
            auth_enabled: false
            storage:
              type: 'filesystem'
            schema_config:
              configs:
                - from: 2024-01-01
                  store: tsdb
                  object_store: filesystem
                  schema: v13
                  index:
                    prefix: loki_index_
                    period: 24h
    - repoURL: https://gitlab.com/dov_bugbear/infrastructure.git
      targetRevision: HEAD
      path: k8s/manifests/grafana/loki