---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mailu
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: mailu
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  destination:
    name: in-cluster
    namespace: mailu
  project: default
  source:
    repoURL: https://mailu.github.io/helm-charts/
    chart: mailu
    targetRevision:  2.1.2
    helm:
      values: |
        fullnameOverride: mailu
        hostnames:
          - mx1.bugbear.fr
        domain: bugbear.fr
        initialAccount:
          enabled: true
          username: admin

        externalDatabase:
          enabled: true
          type: postgresql
          host: bugbear-main-cluster.postgres.svc.cluster.local
          port: 5432
          database: mailu
          existingSecret: mailu.mailu.bugbear-main-cluster.credentials



---

