apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argocd
spec:
  project: default
  destination:
    namespace: postgres-operator
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://gitlab.com/dov_bugbear/infrastructure.git
    targetRevision: HEAD
    path: k8s/manifests/postgres-operator
