apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-secrets
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    name: in-cluster
  source:
    repoURL: https://gitlab.com/dov_bugbear/infrastructure.git
    targetRevision: HEAD
    path: k8s/manifests/helm-secrets
