apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime
  namespace: argocd
spec:
  project: default
  destination:
    namespace: uptime
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
  source:
    repoURL: https://gitlab.com/dov_bugbear/infrastructure.git
    targetRevision: HEAD
    path: k8s/manifests/uptime
