---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: in-cluster-vault-secrets-operator
  labels:
    app: vault-secrets-operator
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: vault-secrets-operator
  source:
    repoURL: https://ricoberger.github.io/helm-charts
    chart: vault-secrets-operator
    targetRevision: 2.6.0
    helm:
      values: |
        fullnameOverride: vault-secrets-operator
        vault:
          authMethod: approle
          appRolePath: auth/approle
          reconciliationTime: 60
          address: https://vault.bugbear.fr
        environmentVars:
          - name: VAULT_ROLE_ID
            valueFrom:
              secretKeyRef:
                name: vault-approle
                key: VAULT_ROLE_ID
          - name: VAULT_SECRET_ID
            valueFrom:
              secretKeyRef:
                name: vault-approle
                key: VAULT_SECRET_ID
          - name: VAULT_TOKEN_MAX_TTL
            valueFrom:
              secretKeyRef:
                name: vault-approle
                key: VAULT_TOKEN_MAX_TTL
