apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: grafana-auth-oidc
  namespace: grafana
spec:
  path: secret/data/grafana/auth_oidc
  keys:
    - OIDC_CLIENT_ID
    - OIDC_CLIENT_SECRET
  templates:
    client_id: "{% .Secrets.OIDC_CLIENT_ID %}"
    client_secret: "{% .Secrets.OIDC_CLIENT_SECRET %}"
  type: Opaque

---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: grafana-smtp
  namespace: grafana
spec:
  path: secret/data/grafana/smtp
  keys:
    - user
    - password
  type: Opaque